language: bash
sudo: required

env:
  - IMAGE_NAME=xtermi2/kibana-searchguard

services:
  - docker

script:
  - docker build --build-arg VCS_REF=$TRAVIS_COMMIT --build-arg BUILD_DATE=`date --iso-8601=seconds` -t $IMAGE_NAME .
after_script:
  - docker inspect $IMAGE_NAME